name: Deploy

on:
  push:
    branches: [main]

  schedule:
    - cron: '*/60 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      # Install
      - name: Install dependencies
        run: bundle install --deployment


      # Test
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bin/rspec

      # Build
      - name: Build
        run: bin/build
        env:
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}

      # Deploy
      - name: Copying files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          rm: true
          source: dist/
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1 # remove "www/" on target
